### ISSUE TITLE
Consider using an event-based state generation (not to be confused with event sourcing, which could also work)

### ISSUE THREAD

**Issue by tclasen** [jdutheil/booking-ddd#1]
To solve:

https://github.com/jddw-dev/booking-ddd/blob/f2d6694ee69d5fec343ca45c98130f9fcd8af40c/TODO#L2

consider that each aggregate is just a fancy state-machine. Regardless of if you are storing state directly or only storing the events (event sourcing) you should only be mutating the internal state of the aggregate via events. When a command it sent to the aggregate, it will check to ensure that the command is valid and that the side-effects that command will cause are also valid in the given context. But the commands themselves don't mutate anything, they express a desire to mutate (usually). The aggregate would then fire off (or just return or internally queue up) a list of events to process. These events being processed are what cause the aggregate to change internal state. If your aggregate is a state-machine, then a command is a request to change the state, and the resulting events are the individual edges followed one by one until you get to your desired state expressed by the command.

Once you have that modeled testing becomes extremely simple!

Given: app = Application([already, existing, events, modeling, desired, starting, conditions])
When:  events = app.handle(NewCommand("Do the thing"))
Then:  assert events == [desired, observed, effects, and, mutations]

If your events are moving around in some internal event-bus, you can swap it out in your tests for a test-specific implementation that makes it easier to capture and assert on the events passing through it.

**Comment by jdutheil** [comment]
I have to say I'm having a hard time getting this one. I guess I still have difficulties separating the domain logic from the storage itself (ie database in here). 

If I take the "RegisterBookerCommand" as an example, I call BookerEntity.create and then I call my repository to save it ; should the repository call be outside of the command ? Like the BookerEntity.create store an event, and at one time (when ?) all events are fired from the entity, and catch elsewhere by a handler that will call the repository ?
